# Generated by Django 4.2.30 on 2026-04-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusinessAxis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('axis', models.CharField(choices=[('it_engineering', 'ITエンジニアリング'), ('hr_recruitment', '人材紹介・採用支援'), ('marketing', 'マーケティング・広告'), ('design', 'デザイン・クリエイティブ'), ('consulting', 'コンサルティング'), ('sales', '営業・セールス'), ('education', '教育・研修・コーチング'), ('writing', 'ライティング・メディア'), ('event_community', 'イベント・コミュニティ'), ('other', 'その他')], max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_axes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userbusinessaxis',
            constraint=models.UniqueConstraint(fields=('owner', 'axis'), name='unique_axis_per_user'),
        ),
    ]
