# Generated by Django 4.2.30 on 2026-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_pro_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_done',
            field=models.BooleanField(default=False),
        ),
    ]
